/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author YULIAN
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        JBba = new javax.swing.JButton();
        JBCle = new javax.swing.JButton();
        JBclear = new javax.swing.JButton();
        JBmn = new javax.swing.JButton();
        JBra = new javax.swing.JButton();
        JB7 = new javax.swing.JButton();
        JB8 = new javax.swing.JButton();
        JB9 = new javax.swing.JButton();
        JBdiv = new javax.swing.JButton();
        JBporce = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        JB5 = new javax.swing.JButton();
        JB6 = new javax.swing.JButton();
        JBmul = new javax.swing.JButton();
        JBdivx = new javax.swing.JButton();
        JB1 = new javax.swing.JButton();
        JB2 = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        JBres = new javax.swing.JButton();
        JBigual = new javax.swing.JButton();
        JB0 = new javax.swing.JButton();
        JBpunto = new javax.swing.JButton();
        JBsuma = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 330, 80));

        JBba.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBba.setText("<-");
        JBba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbaActionPerformed(evt);
            }
        });
        getContentPane().add(JBba, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 50, 40));

        JBCle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBCle.setText("CE");
        JBCle.setPreferredSize(new java.awt.Dimension(73, 23));
        JBCle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCleActionPerformed(evt);
            }
        });
        getContentPane().add(JBCle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 50, 40));

        JBclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBclear.setText("C");
        JBclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBclearActionPerformed(evt);
            }
        });
        getContentPane().add(JBclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 50, 40));

        JBmn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBmn.setText("+-");
        JBmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBmnActionPerformed(evt);
            }
        });
        getContentPane().add(JBmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 50, 40));

        JBra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBra.setText("Raiz");
        getContentPane().add(JBra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 50, 40));

        JB7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB7.setText("7");
        getContentPane().add(JB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 182, 50, 40));

        JB8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB8.setText("8");
        getContentPane().add(JB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 182, 50, 40));

        JB9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB9.setText("9");
        getContentPane().add(JB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 182, 50, 40));

        JBdiv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBdiv.setText("/");
        getContentPane().add(JBdiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 182, 50, 40));

        JBporce.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBporce.setText("%");
        getContentPane().add(JBporce, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 182, 50, 40));

        JB4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB4.setText("4");
        getContentPane().add(JB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 234, 50, 40));

        JB5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB5.setText("5");
        getContentPane().add(JB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 234, 50, 40));

        JB6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB6.setText("6");
        getContentPane().add(JB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 234, 50, 40));

        JBmul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBmul.setText("*");
        getContentPane().add(JBmul, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 234, 50, 40));

        JBdivx.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBdivx.setText("1/x");
        getContentPane().add(JBdivx, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 234, 50, 40));

        JB1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB1.setText("1");
        JB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB1MouseClicked(evt);
            }
        });
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });
        getContentPane().add(JB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 286, 50, 40));

        JB2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB2.setText("2");
        getContentPane().add(JB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 286, 50, 40));

        JB3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB3.setText("3");
        getContentPane().add(JB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 286, 50, 40));

        JBres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBres.setText("-");
        getContentPane().add(JBres, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 286, 50, 40));

        JBigual.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        JBigual.setText("=");
        getContentPane().add(JBigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 286, 50, 92));

        JB0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JB0.setText("0");
        JB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB0ActionPerformed(evt);
            }
        });
        getContentPane().add(JB0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 338, 120, 40));

        JBpunto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBpunto.setText(".");
        getContentPane().add(JBpunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 338, 50, 40));

        JBsuma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBsuma.setText("+");
        getContentPane().add(JBsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 338, 50, 40));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 330, 80));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 30, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBbaActionPerformed

    private void JBCleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBCleActionPerformed

    private void JBclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBclearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBclearActionPerformed

    private void JBmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBmnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBmnActionPerformed

    private void JB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JB1MouseClicked

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB1ActionPerformed

    private void JB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB0ActionPerformed
        
    }//GEN-LAST:event_JB0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB0;
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB6;
    private javax.swing.JButton JB7;
    private javax.swing.JButton JB8;
    private javax.swing.JButton JB9;
    private javax.swing.JButton JBCle;
    private javax.swing.JButton JBba;
    private javax.swing.JButton JBclear;
    private javax.swing.JButton JBdiv;
    private javax.swing.JButton JBdivx;
    private javax.swing.JButton JBigual;
    private javax.swing.JButton JBmn;
    private javax.swing.JButton JBmul;
    private javax.swing.JButton JBporce;
    private javax.swing.JButton JBpunto;
    private javax.swing.JButton JBra;
    private javax.swing.JButton JBres;
    private javax.swing.JButton JBsuma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
